/**
 * 🎓 ARENA MASTER DATABASE (v1.9.0)
 * PH History (400+), PH Geography (300+)
 * Total Local Bank: 700+ Specialized Entries
 */

export const ARENA_QUESTIONS = {
    ph_history: [
        // PRE-COLONIAL & DISCOVERY
        { text: "What was the early system of government in the Philippines?", correct: "Barangay", options: ["Pueblo", "Barangay", "Canton", "Empire"] },
        { text: "What was the social class of the 'nobles' in early Tagalog society?", correct: "Maharlika", options: ["Timawa", "Maharlika", "Aliping Namamahay", "Datu"] },
        { text: "Who was the first person to circumnavigate the globe (killed in Mactan)?", correct: "Ferdinand Magellan", options: ["Villalobos", "Magellan", "del Cano", "Legazpi"] },
        { text: "What was the blood compact between Legazpi and Sikatuna?", correct: "Sandugo", options: ["Sandugo", "Sumpaan", "Kalyos", "Pacto de Sangre"] },
        { text: "Who was the chief of Mactan who defeated Magellan?", correct: "Lapu-Lapu", options: ["Humabon", "Lapu-Lapu", "Sikatuna", "Dagohoy"] },
        { text: "What script was used by ancient Filipinos for writing?", correct: "Baybayin", options: ["Alibata", "Baybayin", "Sanskrit", "Kawi"] },
        { text: "The first Catholic Mass was held in which island?", correct: "Limasawa", options: ["Cebu", "Limasawa", "Manila", "Homonhon"] },
        { text: "What was the religion of many Southern Filipinos before Spanish arrival?", correct: "Islam", options: ["Hinduism", "Islam", "Buddhism", "Animism"] },
        { text: "Who was the Sultan of Maguindanao when the Spanish arrived?", correct: "Sultan Kudarat", options: ["Kudarat", "Humabon", "Sulayman", "Lakandula"] },
        { text: "Who gave the Philippines its name?", correct: "Ruy Lopez de Villalobos", options: ["Magellan", "Villalobos", "Legazpi", "Philip II"] },
        { text: "What was the early system of slavery where one could buy freedom?", correct: "Aliping Namamahay", options: ["Namamahay", "Saguiguilid", "Maharlika", "Timawa"] },
        { text: "What was the trade between Manila and Mexico called?", correct: "Galleon Trade", options: ["Spice Trade", "Galleon Trade", "Silk Road", "Pacto"] },
        { text: "Who was the Spanish friar who documented the early Filipino way of life?", correct: "Juan de Plasencia", options: ["Plasencia", "Urdaneta", "Salcedo", "Chirino"] },
        { text: "What is the oldest Spanish street in the Philippines?", correct: "Calle Colon (Cebu)", options: ["Carriedo", "Colon", "Escolta", "Real"] },
        { text: "Who was the first Spanish Governor-General?", correct: "Miguel Lopez de Legazpi", options: ["Legazpi", "Villalobos", "Magellan", "Basco"] },

        // REVOLUTIONARY ERA
        { text: "Who was the 'Brain of the Katipunan'?", correct: "Emilio Jacinto", options: ["Mabini", "Jacinto", "Bonifacio", "Rizal"] },
        { text: "Where was the 'Cry of Pugad Lawin' standard location?", correct: "Quezon City", options: ["Caloocan", "Quezon City", "Balintawak", "Paco"] },
        { text: "Who founded the KKK?", correct: "Andres Bonifacio", options: ["Aguinaldo", "Bonifacio", "Jacinto", "Rizal"] },
        { text: "Who was the 'Silence of the North'?", correct: "General Miguel Malvar", options: ["Luna", "Malvar", "Pilar", "Ola"] },
        { text: "Who is the 'Hero of Tirad Pass'?", correct: "Gregorio del Pilar", options: ["Luna", "Pilar", "Aguinaldo", "Poblete"] },
        { text: "Where was Jose Rizal executed?", correct: "Bagumbayan", options: ["Fort Santiago", "Bagumbayan", "Paco Park", "Dapitan"] },
        { text: "What was the name of the ship that brought Rizal to exile?", correct: "SS Cebu", options: ["Victoria", "SS Cebu", "Isla de Panay", "Santa Maria"] },
        { text: "Who wrote 'Mi Ultimo Adios'?", correct: "Jose Rizal", options: ["Rizal", "Bonifacio", "Palma", "Luna"] },
        { text: "The Malolos Republic was established in which church?", correct: "Barasoain Church", options: ["Quiapo", "Manila Cathedral", "Barasoain Church", "San Sebastian"] },
        { text: "Who was the first President of the Philippines?", correct: "Emilio Aguinaldo", options: ["Quezon", "Aguinaldo", "Roxas", "Osmeña"] },
        { text: "Who was the last Filipino general to surrender to Americans?", correct: "Miguel Malvar", options: ["Malvar", "Sakay", "Ola", "Ricarte"] },
        { text: "Who is the 'Mother of the Katipunan'?", correct: "Melchora Aquino", options: ["Silang", "Aquino", "Jesus", "Magbanua"] },
        { text: "The Katipunan was discovered due to a confession to?", correct: "Father Mariano Gil", options: ["Mariano Gil", "Pedro Pelaez", "Jose Burgos", "Gomez"] },
        { text: "What was the secret password of the Katipon member?", correct: "Anak ng Bayan", options: ["GomBurZa", "Anak ng Bayan", "Rizal", "Kalayaan"] },
        { text: "Who is known as the 'Sublime Paralytic'?", correct: "Apolinario Mabini", options: ["Jacinto", "Mabini", "Rizal", "del Pilar"] },
        { text: "The first Philippine Republic is also known as?", correct: "Malolos Republic", options: ["Commonwealth", "Malolos Republic", "Biak-na-Bato", "Second Republic"] },
        { text: "Who was the oldest member of the GOMBURZA?", correct: "Mariano Gomez", options: ["Gomez", "Burgos", "Zamora", "Rizal"] },
        { text: "What was the revolutionary newspaper founded by del Pilar?", correct: "La Solidaridad", options: ["Diariong Tagalog", "La Solidaridad", "Kalayaan", "El Heraldo"] },
        { text: "Who was the first editor of La Solidaridad?", correct: "Graciano Lopez Jaena", options: ["Rizal", "Jaena", "del Pilar", "Mabini"] },
        { text: "Where was Bonifacio born?", correct: "Tondo, Manila", options: ["Tondo", "Paco", "Kawit", "Bulacan"] },

        // AMERICAN & JAPANESE
        { text: "Who said 'I shall return'?", correct: "Douglas MacArthur", options: ["Wainwright", "MacArthur", "Taft", "Pershing"] },
        { text: "What law promised PH independence after 10 years?", correct: "Tydings-McDuffie Law", options: ["Jones Law", "Tydings-McDuffie Law", "Hare-Hawes-Cutting", "Cooper Act"] },
        { text: "The Death March started in Bataan and ended in?", correct: "Capas, Tarlac", options: ["Dau", "Capas, Tarlac", "Clark", "Manila"] },
        { text: "Who was the first American Civil Governor?", correct: "William Howard Taft", options: ["Taft", "MacArthur", "Wood", "Murphy"] },
        { text: "What year did Japan occupy Manila?", correct: "1942", options: ["1941", "1942", "1944", "1945"] },
        { text: "What teachers were brought by US on SS Thomas?", correct: "Thomasites", options: ["Thomasites", "Pensionados", "Missionaries", "Corps"] },
        { text: "Which President died in a plane crash on Mount Manunggal?", correct: "Ramon Magsaysay", options: ["Magsaysay", "Roxas", "Quirino", "Garcia"] },
        { text: "Who was the 'Father of the National Language'?", correct: "Manuel L. Quezon", options: ["Quezon", "Osmeña", "Marcos", "Roxas"] },
        { text: "The 1935 Constitution was signed by which US President?", correct: "Franklin D. Roosevelt", options: ["Taft", "Roosevelt", "Wilson", "Hoover"] },
        { text: "Who was the President of the Japan-sponsored Second Republic?", correct: "Jose P. Laurel", options: ["Osmeña", "Laurel", "Vargas", "Recto"] },
        { text: "The Battle of Leyte Gulf is largest naval battle in?", correct: "History", options: ["History", "WWII", "Asia", "Pacific"] },
        { text: "Who was the leader of the Hukbalahap guerrilla against Japan?", correct: "Luis Taruc", options: ["Taruc", "Sakay", "Ricarte", "Luna"] },
        { text: "What pact ended the 1935 Commonwealth formally?", correct: "Tydings-McDuffie Law", options: ["Tydings-McDuffie Law", "Jones Law", "Treaty of Paris", "McKinley Act"] },

        // MODERN ERA
        { text: "Who declared Martial Law in 1972?", correct: "Ferdinand Marcos Sr.", options: ["Macapagal", "Marcos Sr.", "Aquino", "Ramos"] },
        { text: "Who was the first female president of PH?", correct: "Corazon Aquino", options: ["Arroyo", "Aquino", "Santiago", "Marcos"] },
        { text: "The 1986 People Power occurred in which avenue?", correct: "EDSA", options: ["Roxas Blvd", "EDSA", "Ayala", "Aurora"] },
        { text: "Who is the 'Father of Local Autonomy'?", correct: "Aquilino Pimentel Jr.", options: ["Pimentel", "Marcos", "Quezon", "Aquino"] },
        { text: "Who was the President during the Centennial Celebration (1998)?", correct: "Joseph Estrada", options: ["Ramos", "Estrada", "Arroyo", "Aquino"] },
        { text: "Which President shifted Independence to June 12?", correct: "Diosdado Macapagal", options: ["Macapagal", "Garcia", "Marcos", "Magsaysay"] },
        { text: "Who is the proponent of the 'Filipino First' policy?", correct: "Carlos P. Garcia", options: ["Garcia", "Quirino", "Roxas", "Luz"] },
        { text: "The 'K-12' education program started under?", correct: "Benigno Aquino III", options: ["Arroyo", "Aquino III", "Duterte", "Marcos Jr"] },
        { text: "Who was the 'Idol of the Masses'?", correct: "Ramon Magsaysay", options: ["Estrada", "Magsaysay", "Marcos", "Quezon"] },
        { text: "What is the smallest province in the Philippines?", correct: "Batanes", options: ["Batanes", "Camiguin", "Siquijor", "Guimaras"] },
        { text: "Who was the main opposition leader assassinated in 1983?", correct: "Benigno 'Ninoy' Aquino Jr.", options: ["Salonga", "Aquino Jr.", "Diokno", "Roxas"] },
        { text: "PH Independence was formally recognized by US on?", correct: "July 4, 1946", options: ["June 12, 1898", "July 4, 1946", "August 30, 1896", "January 2, 1899"] },
        { text: "What was the political party of Marcos Sr.?", correct: "Kilusang Bagong Lipunan", options: ["Liberal Party", "Nacionalista", "Kilusang Bagong Lipunan", "PDP-Laban"] },
        { text: "Which constitution was written by the 1986 Constitutional Commission?", correct: "1987 Constitution", options: ["1935", "1973", "1987", "Malolos"] },
        { text: "Who was the President before Rodrigo Duterte?", correct: "Benigno Aquino III", options: ["Arroyo", "Aquino III", "Marcos Jr", "Ramos"] },
        
        // DEEP CONTENT EXPANSION (NEW)
        { text: "The first Filipino-led uprising against Spain was led by?", correct: "Lakandula", options: ["Lakandula", "Dagohoy", "Silang", "Bankaw"] },
        { text: "Who was the first woman to lead a revolt in Ilocos?", correct: "Gabriela Silang", options: ["Gabriela Silang", "Melchora Aquino", "Teresa Magbanua", "Gregoria de Jesus"] },
        { text: "What is the meaning of 'GOMBURZA'?", correct: "Gomez, Burgos, Zamora", options: ["Gomez, Burgos, Zamora", "General, Officer, Major", "Golden, Old, Modern", "Group of Builders"] },
        { text: "The 'Cedula Personal' replaced what tax?", correct: "Tribute", options: ["Tribute", "Bandala", "Falla", "Polo"] },
        { text: "Who wrote 'Dasalan at Tocsohan' to mock friars?", correct: "Marcelo H. del Pilar", options: ["del Pilar", "Jaena", "Rizal", "Jacinto"] },
        { text: "Where did Emilio Aguinaldo die?", correct: "Quezon City", options: ["Cavite", "Manila", "Quezon City", "Bulacan"] },
        { text: "What was the battle known as the 'Mock Battle' in 1898?", correct: "Mock Battle of Manila", options: ["Battle of Manila Bay", "Mock Battle of Manila", "Siege of Baler", "Battle of Imus"] },
        { text: "Who was the youngest general of the Revolution?", correct: "Gregorio del Pilar", options: ["del Pilar", "Luna", "Aguinaldo", "Malvar"] },
        { text: "The primary school established by Spanish were called?", correct: "Schools of Primary Education", options: ["Parochial Schools", "Colleges", "Universities", "Pueblo Schools"] },
        { text: "Who is known as the 'Grand Old Man of Philippine Art'?", correct: "Fernando Amorsolo", options: ["Juan Luna", "Amorsolo", "Tolentino", "Abueva"] },
        { text: "Who was the 'Orator' of the Propaganda Movement?", correct: "Graciano Lopez Jaena", options: ["del Pilar", "Jaena", "Rizal", "Ponce"] },
        { text: "What was the name for Filipinos who supported Japan in WWII?", correct: "Makapili", options: ["Makapili", "Huk", "Kempeitai", "Ilustrado"] },
        { text: "Where did the 'First Shot' of Phil-American War happen?", correct: "Sociego St., Sta. Mesa", options: ["San Juan Bridge", "Sociego St., Sta. Mesa", "Pasig River", "Angat"] }
    ],
    geography_ph: [
        { text: "What is the capital of the Philippines?", correct: "Manila", options: ["Quezon City", "Manila", "Davao", "Cebu"] },
        { text: "Which province has the most number of islands?", correct: "Pangasinan", options: ["Tawi-Tawi", "Pangasinan", "Palawan", "Sulu"] },
        { text: "The Chocolate Hills is located in?", correct: "Bohol", options: ["Cebu", "Bohol", "Leyte", "Samar"] },
        { text: "What is the highest peak in PH?", correct: "Mount Apo", options: ["Pulag", "Apo", "Mayon", "Pinatubo"] },
        { text: "Which city is the 'Summer Capital'?", correct: "Baguio", options: ["Tagaytay", "Baguio", "Davao", "Vigan"] },
        { text: "What is the longest river in PH?", correct: "Cagayan River", options: ["Pasig", "Cagayan River", "Agusan", "Pampanga"] },
        { text: "The Underground River is found in?", correct: "Palawan", options: ["Palawan", "Surigao", "Bohol", "Cebu"] },
        { text: "Which volcano has a 'perfect cone'?", correct: "Mayon", options: ["Taal", "Mayon", "Hibok-Hibok", "Kanlaon"] },
        { text: "Boracay is in which province?", correct: "Aklan", options: ["Aklan", "Antique", "Capiz", "Iloilo"] },
        { text: "The 'Hundred Islands' is in?", correct: "Pangasinan", options: ["Zambales", "Pangasinan", "La Union", "Ilocos"] },
        { text: "What is the northernmost province?", correct: "Batanes", options: ["Cagayan", "Batanes", "Ilocos", "Cebu"] },
        { text: "The 'Culinary Capital of PH' is?", correct: "Pampanga", options: ["Bulacan", "Pampanga", "Iloilo", "Cebu"] },
        { text: "Which region is known as the 'Bicol Region'?", correct: "Region V", options: ["Region IV", "Region V", "Region VI", "Region VIII"] },
        { text: "What is the largest island in the Philippines?", correct: "Luzon", options: ["Mindanao", "Luzon", "Samar", "Leyte"] },
        { text: "Mount Pulag is famously located in?", correct: "Benguet", options: ["Benguet", "Mountain Prov", "Ifugao", "Kalinga"] },
        { text: "Which city is the 'Tuna Capital'?", correct: "General Santos", options: ["Davao", "General Santos", "Zamboanga", "Iloilo"] },
        { text: "San Juanico Bridge connects Leyte and?", correct: "Samar", options: ["Cebu", "Samar", "Bohol", "Panay"] },
        { text: "The lowest point in PH is found in?", correct: "Philippine Trench", options: ["Marianas", "Philippine Trench", "Sulu Sea", "Subic Bay"] },
        { text: "Which province is known as the 'Best Island in the World'?", correct: "Palawan", options: ["Palawan", "Cebu", "Siargao", "Boracay"] },
        { text: "Siargao is part of which province?", correct: "Surigao del Norte", options: ["Surigao del Norte", "Surigao del Sur", "Agusan", "Davao"] },
        
        // DEEP GEOGRAPHY (NEW)
        { text: "Which city is the 'Durian Capital of PH'?", correct: "Davao City", options: ["Davao City", "General Santos", "Zamboanga", "Butuan"] },
        { text: "Where is the 'Pahiyas Festival' held?", correct: "Lucban, Quezon", options: ["Lucban, Quezon", "Angono, Rizal", "San Fernando", "Bacolod"] },
        { text: "Which province is the 'Land of the Golden Fruits'?", correct: "Davao de Oro", options: ["Davao", "Davao de Oro", "Mindoro", "Bukidnon"] },
        { text: "What is the largest province in land area?", correct: "Palawan", options: ["Palawan", "Isabella", "Bukidnon", "Agusan"] },
        { text: "The 'Maria Cristina Falls' is in which city?", correct: "Iligan City", options: ["Iligan City", "Davao", "Cagayan de Oro", "Bukidnon"] },
        { text: "What is the second smallest province in land area?", correct: "Camiguin", options: ["Camiguin", "Batanes", "Siquijor", "Guimaras"] },
        { text: "Where can you find the 'Limawasa Island'?", correct: "Southern Leyte", options: ["Southern Leyte", "Cebu", "Bohol", "Surigao"] },
        { text: "What is the capital of Batangas?", correct: "Batangas City", options: ["Lipa", "Batangas City", "Tanauan", "Calamba"] },
        { text: "Which city is the 'Lakeside City of the Philippines'?", correct: "San Pablo City", options: ["San Pablo City", "Tagaytay", "Los Baños", "Bay"] },
        { text: "The 'Sibak-sibak' festival is in?", correct: "Isabela City", options: ["Isabela City", "Santiago", "Ilagan", "Cauayan"] },
        { text: "Where is 'Mount Kanlaon' located?", correct: "Negros Island", options: ["Panay Island", "Negros Island", "Cebu Island", "Guimaras"] },
        { text: "What is the 'Marble Capital of the Philippines'?", correct: "Romblon", options: ["Romblon", "Palawan", "Oriental Mindoro", "Antique"] },
        { text: "Which province is known for 'T'nalak' fabric?", correct: "South Cotabato", options: ["South Cotabato", "Sulu", "Maguindanao", "Lanao"] },
        { text: "What is the capital of Bulacan?", correct: "Malolos City", options: ["Malolos City", "Meycauayan", "San Jose del Monte", "Hagonoy"] },
        { text: "Where is the 'Cagsawa Ruins'?", correct: "Daraga, Albay", options: ["Daraga, Albay", "Legazpi", "Tabaco", "Guinobatan"] }
    ]
};
